packages:
  - packages/*
  - packages/@reporunner/*
  - apps/*

auditConfig:
  allowedLicenses:
    - MIT
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC
  ignoreCves: []

catalog:
  '@ant-design/icons': ^6.0.0
  '@ant-design/plots': ^2.6.5
  '@anthropic-ai/sdk': ^0.57.0
  '@biomejs/biome': ^2.2.5
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@emotion/react': ^11.11.0
  '@emotion/styled': ^11.11.0
  '@langchain/core': ^0.3.26
  '@radix-ui/react-alert-dialog': ^1.0.4
  '@radix-ui/react-dropdown-menu': ^2.0.5
  '@radix-ui/react-popover': ^1.0.6
  '@radix-ui/react-select': ^1.2.2
  '@radix-ui/react-tabs': ^1.0.4
  '@radix-ui/react-toast': ^1.1.4
  '@radix-ui/react-tooltip': ^1.0.6
  '@reactflow/background': ^11.3.14
  '@reactflow/controls': ^11.2.14
  '@reactflow/minimap': ^11.7.14
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-virtual': ^3.13.12
  '@testing-library/jest-dom': ^6.8.0
  '@testing-library/react': ^16.3.0
  '@types/bcryptjs': ^2.4.6
  '@types/compression': ^1.8.1
  '@types/cors': ^2.8.17
  '@types/express': 4.17.23
  '@types/jest': ^29.5.3
  '@types/jsonwebtoken': ^9.0.5
  '@types/lodash': ^4.17.20
  '@types/morgan': ^1.9.9
  '@types/node': ^24.6.2
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@types/supertest': ^6.0.2
  '@vitejs/plugin-react': ^4.6.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  antd: ^5.26.4
  autoprefixer: ^10.4.21
  axios: ^1.10.0
  bcryptjs: ^2.4.3
  bull: ^4.12.0
  bullmq: ^5.1.5
  chromadb: ^1.7.0
  class-variance-authority: ^0.7.1
  cohere-ai: ^7.0.0
  compression: ^1.7.4
  cors: ^2.8.5
  cron: ^3.1.0
  dotenv: ^16.3.1
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  eventemitter3: ^5.0.0
  express: ^4.19.2
  express-async-errors: ^3.1.1
  express-validator: ^7.2.1
  fastify: ^5.3.0
  google-auth-library: ^9.4.2
  googleapis: ^132.0.0
  helmet: ^7.1.0
  ioredis: ^5.3.2
  jest: ^29.6.2
  jsonwebtoken: ^9.0.2
  lodash: ^4.17.21
  lucide-react: ^0.536.0
  mongodb: ^6.0.0
  mongoose: ^8.1.1
  morgan: ^1.10.0
  multer: ^2.0.2
  node-cron: ^3.0.3
  openai: ^4.24.7
  p-limit: ^5.0.0
  p-queue: ^8.0.1
  pg: ^8.16.3
  pgvector: ^0.2.1
  postcss: ^8.5.6
  postgres: ^3.4.5
  react: ^19.1.0
  react-dom: ^19.1.0
  react-hook-form: ^7.44.2
  react-hot-toast: ^2.6.0
  react-router-dom: ^7.6.3
  reactflow: ^11.11.4
  recharts: ^3.2.1
  rollup-plugin-visualizer: ^6.0.3
  socket.io: ^4.7.4
  socket.io-client: ^4.8.1
  supertest: ^6.3.4
  tailwindcss: ^3.4.17
  tiktoken: ^1.0.0
  tsc-alias: ^1.8.8
  tsup: ^8.5.0
  tsx: ^4.7.0
  turbo: ^2.5.6
  typescript: ^5.9.3
  vite: ^7.0.4
  vitest: ^3.2.4
  winston: ^3.11.0
  ws: ^8.14.0
  zod: ^4.1.11
  zustand: ^5.0.6

enableGlobalCache: true

enableGlobalHoist: true

engines: {node: '>=18.0.0', pnpm: '>=8.0.0'}

packageExtensions:
  '@reactflow/background':
    peerDependencies:
      reactflow: '*'
  '@reactflow/controls':
    peerDependencies:
      reactflow: '*'
  '@reactflow/minimap':
    peerDependencies:
      reactflow: '*'
  openai:
    peerDependencies:
      zod: '*'

packageManager: pnpm@9.15.2

shamefullyHoist: false

storeDir: ~/.pnpm-store

virtualStoreDir: node_modules/.pnpm
