// Compatibility shim to avoid duplicate implementations.
// Re-export the canonical AI Model service and related types/instance
// from the consolidated service file one level up.

export {
  AIModelService,
  aiModelService,
  type AIModel,
  type ModelConfiguration,
  type ModelParameters,
  type DataSchema,
  type DataField,
  type FieldConstraints,
  type ValidationRules,
  type ModelMetrics,
  type TrainingConfiguration,
  type DatasetConfiguration,
  type PreprocessingStep,
  type DataAugmentation,
  type AugmentationTechnique,
  type OptimizerConfig,
  type SchedulerConfig,
  type EarlyStoppingConfig,
  type CheckpointConfig,
  type DistributedConfig,
  type DeploymentConfiguration,
  type InfrastructureConfig,
  type ResourceLimits,
  type ScalingConfig,
  type MonitoringConfig,
  type AlertingConfig,
  type EscalationPolicy,
  type EscalationLevel,
  type SecurityConfig,
  type RateLimitConfig,
  type VersioningConfig,
  type HealthCheckConfig,
  type TrafficSplittingConfig,
  type SuccessCriteria,
  type TrainingJob,
  type TrainingMetrics,
  type TrainingLog,
  type ResourceUsage,
  type ModelEvaluation,
  type EvaluationResults,
  type PredictionResult,
  type ErrorAnalysis,
} from '../aiModelService';

export default AIModelService;

