#!/bin/bash
# ============================================
# KlikkFlow - Environment File Generator
# ============================================
# Generates .env file from GitHub Secrets

set -euo pipefail

OUTPUT=".env"

while [[ $# -gt 0 ]]; do
    case $1 in
        --output) OUTPUT="$2"; shift 2 ;;
        --mongodb-uri) MONGODB_URI="$2"; shift 2 ;;
        --postgres-url) POSTGRES_URL="$2"; shift 2 ;;
        --postgres-password) POSTGRES_PASSWORD="$2"; shift 2 ;;
        --redis-url) REDIS_URL="$2"; shift 2 ;;
        --jwt-secret) JWT_SECRET="$2"; shift 2 ;;
        --encryption-key) ENCRYPTION_KEY="$2"; shift 2 ;;
        --session-secret) SESSION_SECRET="$2"; shift 2 ;;
        --openai-key) OPENAI_KEY="$2"; shift 2 ;;
        --anthropic-key) ANTHROPIC_KEY="$2"; shift 2 ;;
        --google-client-id) GOOGLE_CLIENT_ID="$2"; shift 2 ;;
        --google-client-secret) GOOGLE_CLIENT_SECRET="$2"; shift 2 ;;
        --github-client-id) GITHUB_CLIENT_ID="$2"; shift 2 ;;
        --github-client-secret) GITHUB_CLIENT_SECRET="$2"; shift 2 ;;
        --slack-bot-token) SLACK_BOT_TOKEN="$2"; shift 2 ;;
        --slack-signing-secret) SLACK_SIGNING_SECRET="$2"; shift 2 ;;
        --sentry-dsn) SENTRY_DSN="$2"; shift 2 ;;
        --grafana-password) GRAFANA_PASSWORD="$2"; shift 2 ;;
        --smtp-host) SMTP_HOST="$2"; shift 2 ;;
        --smtp-user) SMTP_USER="$2"; shift 2 ;;
        --smtp-pass) SMTP_PASS="$2"; shift 2 ;;
        --cors-origin) CORS_ORIGIN="$2"; shift 2 ;;
        --frontend-url) FRONTEND_URL="$2"; shift 2 ;;
        --backend-url) BACKEND_URL="$2"; shift 2 ;;
        *) shift ;;
    esac
done

echo "Generating environment file: $OUTPUT"

cat > "$OUTPUT" << EOF
# Generated by GitHub Actions on $(date)
NODE_ENV=production

# Database
MONGODB_URI=${MONGODB_URI:-}
POSTGRES_URL=${POSTGRES_URL:-}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
REDIS_URL=${REDIS_URL:-}

# Security
JWT_SECRET=${JWT_SECRET:-}
CREDENTIAL_ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
SESSION_SECRET=${SESSION_SECRET:-}

# AI Services
OPENAI_API_KEY=${OPENAI_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY:-}

# OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}

# Integrations
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET:-}

# Monitoring
SENTRY_DSN=${SENTRY_DSN:-}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-}

# Email
SMTP_HOST=${SMTP_HOST:-}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}

# CORS
CORS_ORIGIN=${CORS_ORIGIN:-}

# URLs
FRONTEND_URL=${FRONTEND_URL:-}
BACKEND_URL=${BACKEND_URL:-}

# Feature Flags
ENABLE_AI_FEATURES=true
ENABLE_REAL_TIME=true
ENABLE_ANALYTICS=true
EOF

chmod 600 "$OUTPUT"
echo "✓ Environment file created: $OUTPUT"
